/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window1 (void);
GtkWidget* create_window2 (void);
GtkWidget* create_window_option (void);
GtkWidget* create_window_delete (void);
GtkWidget* create_window_update (void);
GtkWidget* create_window_update_index (void);
