/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *fixed1;
  GtkWidget *entry1;
  GtkWidget *entry2;
  GtkWidget *label14;
  GtkWidget *label1;
  GtkWidget *label2;
  GtkWidget *button1;
  GtkWidget *button2;
  GtkWidget *label_st;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("LOGIN"));
  gtk_window_set_position (GTK_WINDOW (window1), GTK_WIN_POS_CENTER_ALWAYS);
  gtk_window_set_default_size (GTK_WINDOW (window1), 500, 300);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (window1), fixed1);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed1), entry1, 192, 64);
  gtk_widget_set_size_request (entry1, 208, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed1), entry2, 192, 128);
  gtk_widget_set_size_request (entry2, 216, 32);
  gtk_entry_set_visibility (GTK_ENTRY (entry2), FALSE);

  label14 = gtk_label_new (_("Welcome to DMMD"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed1), label14, 96, 8);
  gtk_widget_set_size_request (label14, 312, 32);

  label1 = gtk_label_new (_("Username"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 40, 64);
  gtk_widget_set_size_request (label1, 120, 32);

  label2 = gtk_label_new (_("Password"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed1), label2, 24, 128);
  gtk_widget_set_size_request (label2, 136, 32);

  button1 = gtk_button_new_with_mnemonic (_("LOGIN"));
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed1), button1, 104, 232);
  gtk_widget_set_size_request (button1, 96, 40);

  button2 = gtk_button_new_with_mnemonic (_("EXIT"));
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed1), button2, 264, 232);
  gtk_widget_set_size_request (button2, 88, 40);

  label_st = gtk_label_new ("");
  gtk_widget_show (label_st);
  gtk_fixed_put (GTK_FIXED (fixed1), label_st, 128, 184);
  gtk_widget_set_size_request (label_st, 264, 24);

  g_signal_connect ((gpointer) window1, "destroy",
                    G_CALLBACK (on_login_destroy),
                    NULL);
  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (on_login_clicked),
                    NULL);
  g_signal_connect ((gpointer) button2, "clicked",
                    G_CALLBACK (on_exit_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window1, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (window1, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (window1, label14, "label14");
  GLADE_HOOKUP_OBJECT (window1, label1, "label1");
  GLADE_HOOKUP_OBJECT (window1, label2, "label2");
  GLADE_HOOKUP_OBJECT (window1, button1, "button1");
  GLADE_HOOKUP_OBJECT (window1, button2, "button2");
  GLADE_HOOKUP_OBJECT (window1, label_st, "label_st");

  return window1;
}

GtkWidget*
create_window2 (void)
{
  GtkWidget *window2;
  GtkWidget *fixed2;
  GtkWidget *entry_name;
  GtkWidget *entry_roll;
  GtkWidget *entry_branch;
  GtkWidget *entry_mobno;
  GtkWidget *label5;
  GtkWidget *label4;
  GtkWidget *label7;
  GtkWidget *label6;
  GtkWidget *button3;
  GtkWidget *button4;
  GtkWidget *label3;

  window2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window2), _("Main Window"));
  gtk_window_set_position (GTK_WINDOW (window2), GTK_WIN_POS_CENTER_ALWAYS);
  gtk_window_set_default_size (GTK_WINDOW (window2), 600, 600);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (window2), fixed2);

  entry_name = gtk_entry_new ();
  gtk_widget_show (entry_name);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_name, 328, 64);
  gtk_widget_set_size_request (entry_name, 208, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_name), 8226);

  entry_roll = gtk_entry_new ();
  gtk_widget_show (entry_roll);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_roll, 328, 120);
  gtk_widget_set_size_request (entry_roll, 208, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_roll), 8226);

  entry_branch = gtk_entry_new ();
  gtk_widget_show (entry_branch);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_branch, 328, 176);
  gtk_widget_set_size_request (entry_branch, 208, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_branch), 8226);

  entry_mobno = gtk_entry_new ();
  gtk_widget_show (entry_mobno);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_mobno, 328, 232);
  gtk_widget_set_size_request (entry_mobno, 208, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_mobno), 8226);

  label5 = gtk_label_new (_("Roll No"));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed2), label5, 152, 120);
  gtk_widget_set_size_request (label5, 80, 32);

  label4 = gtk_label_new (_("Name"));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed2), label4, 144, 64);
  gtk_widget_set_size_request (label4, 104, 32);

  label7 = gtk_label_new (_("Mob No :"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed2), label7, 152, 232);
  gtk_widget_set_size_request (label7, 104, 40);

  label6 = gtk_label_new (_("Branch"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed2), label6, 136, 176);
  gtk_widget_set_size_request (label6, 104, 32);

  button3 = gtk_button_new_with_mnemonic (_("Save"));
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed2), button3, 152, 360);
  gtk_widget_set_size_request (button3, 104, 40);

  button4 = gtk_button_new_with_mnemonic (_("Exit"));
  gtk_widget_show (button4);
  gtk_fixed_put (GTK_FIXED (fixed2), button4, 352, 360);
  gtk_widget_set_size_request (button4, 104, 40);

  label3 = gtk_label_new ("");
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed2), label3, 32, 296);
  gtk_widget_set_size_request (label3, 560, 48);

  g_signal_connect ((gpointer) window2, "destroy",
                    G_CALLBACK (on_main_window_destroy),
                    NULL);
  g_signal_connect ((gpointer) button3, "clicked",
                    G_CALLBACK (on_Save_clicked),
                    NULL);
  g_signal_connect ((gpointer) button4, "clicked",
                    G_CALLBACK (on_Exit_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window2, window2, "window2");
  GLADE_HOOKUP_OBJECT (window2, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (window2, entry_name, "entry_name");
  GLADE_HOOKUP_OBJECT (window2, entry_roll, "entry_roll");
  GLADE_HOOKUP_OBJECT (window2, entry_branch, "entry_branch");
  GLADE_HOOKUP_OBJECT (window2, entry_mobno, "entry_mobno");
  GLADE_HOOKUP_OBJECT (window2, label5, "label5");
  GLADE_HOOKUP_OBJECT (window2, label4, "label4");
  GLADE_HOOKUP_OBJECT (window2, label7, "label7");
  GLADE_HOOKUP_OBJECT (window2, label6, "label6");
  GLADE_HOOKUP_OBJECT (window2, button3, "button3");
  GLADE_HOOKUP_OBJECT (window2, button4, "button4");
  GLADE_HOOKUP_OBJECT (window2, label3, "label3");

  return window2;
}

GtkWidget*
create_window_option (void)
{
  GtkWidget *window_option;
  GtkWidget *fixed3;
  GtkWidget *button_insert;
  GtkWidget *button_delete;
  GtkWidget *button_logout;
  GtkWidget *button_update;
  GtkWidget *button_search;
  GtkWidget *entry12;
  GtkWidget *label16;
  GtkWidget *label17;
  GtkWidget *label18;

  window_option = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window_option), _("OPTION"));
  gtk_window_set_position (GTK_WINDOW (window_option), GTK_WIN_POS_CENTER);
  gtk_window_set_default_size (GTK_WINDOW (window_option), 500, 500);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (window_option), fixed3);

  button_insert = gtk_button_new_with_mnemonic (_("INSERT"));
  gtk_widget_show (button_insert);
  gtk_fixed_put (GTK_FIXED (fixed3), button_insert, 96, 24);
  gtk_widget_set_size_request (button_insert, 120, 48);

  button_delete = gtk_button_new_with_mnemonic (_("DELETE"));
  gtk_widget_show (button_delete);
  gtk_fixed_put (GTK_FIXED (fixed3), button_delete, 96, 112);
  gtk_widget_set_size_request (button_delete, 120, 48);

  button_logout = gtk_button_new_with_mnemonic (_("LOGOUT"));
  gtk_widget_show (button_logout);
  gtk_fixed_put (GTK_FIXED (fixed3), button_logout, 296, 344);
  gtk_widget_set_size_request (button_logout, 107, 37);

  button_update = gtk_button_new_with_mnemonic (_("UPDATE"));
  gtk_widget_show (button_update);
  gtk_fixed_put (GTK_FIXED (fixed3), button_update, 96, 192);
  gtk_widget_set_size_request (button_update, 120, 48);

  button_search = gtk_button_new_with_mnemonic (_("Search"));
  gtk_widget_show (button_search);
  gtk_fixed_put (GTK_FIXED (fixed3), button_search, 96, 264);
  gtk_widget_set_size_request (button_search, 120, 48);

  entry12 = gtk_entry_new ();
  gtk_widget_show (entry12);
  gtk_fixed_put (GTK_FIXED (fixed3), entry12, 312, 272);
  gtk_widget_set_size_request (entry12, 160, 28);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry12), 8226);

  label16 = gtk_label_new ("");
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed3), label16, 320, 32);
  gtk_widget_set_size_request (label16, 184, 40);

  label17 = gtk_label_new ("");
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed3), label17, 336, 104);
  gtk_widget_set_size_request (label17, 160, 40);

  label18 = gtk_label_new ("");
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed3), label18, 336, 184);
  gtk_widget_set_size_request (label18, 160, 32);

  g_signal_connect ((gpointer) window_option, "destroy",
                    G_CALLBACK (on_option_destroy),
                    NULL);
  g_signal_connect ((gpointer) button_insert, "clicked",
                    G_CALLBACK (on_button_insert_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_delete, "clicked",
                    G_CALLBACK (on_button_delete_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_logout, "clicked",
                    G_CALLBACK (on_button_logout_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_update, "clicked",
                    G_CALLBACK (on_button_update_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_search, "clicked",
                    G_CALLBACK (on_button_search_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_option, window_option, "window_option");
  GLADE_HOOKUP_OBJECT (window_option, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (window_option, button_insert, "button_insert");
  GLADE_HOOKUP_OBJECT (window_option, button_delete, "button_delete");
  GLADE_HOOKUP_OBJECT (window_option, button_logout, "button_logout");
  GLADE_HOOKUP_OBJECT (window_option, button_update, "button_update");
  GLADE_HOOKUP_OBJECT (window_option, button_search, "button_search");
  GLADE_HOOKUP_OBJECT (window_option, entry12, "entry12");
  GLADE_HOOKUP_OBJECT (window_option, label16, "label16");
  GLADE_HOOKUP_OBJECT (window_option, label17, "label17");
  GLADE_HOOKUP_OBJECT (window_option, label18, "label18");

  return window_option;
}

GtkWidget*
create_window_delete (void)
{
  GtkWidget *window_delete;
  GtkWidget *fixed4;
  GtkWidget *entry_delete;
  GtkWidget *button_delete_index;
  GtkWidget *label8;

  window_delete = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window_delete), _("DELETE"));
  gtk_window_set_position (GTK_WINDOW (window_delete), GTK_WIN_POS_CENTER);
  gtk_window_set_default_size (GTK_WINDOW (window_delete), 400, 400);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (window_delete), fixed4);

  entry_delete = gtk_entry_new ();
  gtk_widget_show (entry_delete);
  gtk_fixed_put (GTK_FIXED (fixed4), entry_delete, 208, 88);
  gtk_widget_set_size_request (entry_delete, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_delete), 8226);

  button_delete_index = gtk_button_new_with_mnemonic (_("OK"));
  gtk_widget_show (button_delete_index);
  gtk_fixed_put (GTK_FIXED (fixed4), button_delete_index, 216, 200);
  gtk_widget_set_size_request (button_delete_index, 112, 40);

  label8 = gtk_label_new (_("INDEX"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed4), label8, 64, 88);
  gtk_widget_set_size_request (label8, 96, 32);

  g_signal_connect ((gpointer) window_delete, "destroy",
                    G_CALLBACK (on_window_delete_destroy),
                    NULL);
  g_signal_connect ((gpointer) button_delete_index, "clicked",
                    G_CALLBACK (on_button_delete_index_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_delete, window_delete, "window_delete");
  GLADE_HOOKUP_OBJECT (window_delete, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (window_delete, entry_delete, "entry_delete");
  GLADE_HOOKUP_OBJECT (window_delete, button_delete_index, "button_delete_index");
  GLADE_HOOKUP_OBJECT (window_delete, label8, "label8");

  return window_delete;
}

GtkWidget*
create_window_update (void)
{
  GtkWidget *window_update;
  GtkWidget *fixed5;
  GtkWidget *entry4;
  GtkWidget *entry5;
  GtkWidget *entry6;
  GtkWidget *entry7;
  GtkWidget *button7;
  GtkWidget *label10;
  GtkWidget *label11;
  GtkWidget *label12;
  GtkWidget *label9;

  window_update = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window_update), _("UPDATE"));
  gtk_window_set_position (GTK_WINDOW (window_update), GTK_WIN_POS_CENTER);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (window_update), fixed5);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_fixed_put (GTK_FIXED (fixed5), entry4, 312, 32);
  gtk_widget_set_size_request (entry4, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_fixed_put (GTK_FIXED (fixed5), entry5, 312, 96);
  gtk_widget_set_size_request (entry5, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5), 8226);

  entry6 = gtk_entry_new ();
  gtk_widget_show (entry6);
  gtk_fixed_put (GTK_FIXED (fixed5), entry6, 312, 160);
  gtk_widget_set_size_request (entry6, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6), 8226);

  entry7 = gtk_entry_new ();
  gtk_widget_show (entry7);
  gtk_fixed_put (GTK_FIXED (fixed5), entry7, 312, 224);
  gtk_widget_set_size_request (entry7, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7), 8226);

  button7 = gtk_button_new_with_mnemonic (_("UPDATE"));
  gtk_widget_show (button7);
  gtk_fixed_put (GTK_FIXED (fixed5), button7, 240, 344);
  gtk_widget_set_size_request (button7, 104, 40);

  label10 = gtk_label_new (_("Roll"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed5), label10, 128, 96);
  gtk_widget_set_size_request (label10, 112, 32);

  label11 = gtk_label_new (_("Branch"));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed5), label11, 136, 160);
  gtk_widget_set_size_request (label11, 112, 32);

  label12 = gtk_label_new (_("MOB No"));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed5), label12, 144, 224);
  gtk_widget_set_size_request (label12, 104, 32);

  label9 = gtk_label_new (_("Name"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed5), label9, 136, 32);
  gtk_widget_set_size_request (label9, 104, 32);

  g_signal_connect ((gpointer) window_update, "destroy",
                    G_CALLBACK (on_window_update_destroy),
                    NULL);
  g_signal_connect ((gpointer) button7, "clicked",
                    G_CALLBACK (on_button7_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_update, window_update, "window_update");
  GLADE_HOOKUP_OBJECT (window_update, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (window_update, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (window_update, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (window_update, entry6, "entry6");
  GLADE_HOOKUP_OBJECT (window_update, entry7, "entry7");
  GLADE_HOOKUP_OBJECT (window_update, button7, "button7");
  GLADE_HOOKUP_OBJECT (window_update, label10, "label10");
  GLADE_HOOKUP_OBJECT (window_update, label11, "label11");
  GLADE_HOOKUP_OBJECT (window_update, label12, "label12");
  GLADE_HOOKUP_OBJECT (window_update, label9, "label9");

  return window_update;
}

GtkWidget*
create_window_update_index (void)
{
  GtkWidget *window_update_index;
  GtkWidget *fixed6;
  GtkWidget *entry8;
  GtkWidget *label13;
  GtkWidget *button_index_update;

  window_update_index = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window_update_index), _("UPDATE INDEX"));
  gtk_window_set_position (GTK_WINDOW (window_update_index), GTK_WIN_POS_CENTER_ALWAYS);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (window_update_index), fixed6);

  entry8 = gtk_entry_new ();
  gtk_widget_show (entry8);
  gtk_fixed_put (GTK_FIXED (fixed6), entry8, 176, 112);
  gtk_widget_set_size_request (entry8, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry8), 8226);

  label13 = gtk_label_new (_("ENTER INDEX"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed6), label13, 32, 104);
  gtk_widget_set_size_request (label13, 120, 40);

  button_index_update = gtk_button_new_with_mnemonic (_("OK"));
  gtk_widget_show (button_index_update);
  gtk_fixed_put (GTK_FIXED (fixed6), button_index_update, 184, 224);
  gtk_widget_set_size_request (button_index_update, 120, 48);

  g_signal_connect ((gpointer) window_update_index, "destroy",
                    G_CALLBACK (on_window_update_index_destroy),
                    NULL);
  g_signal_connect ((gpointer) button_index_update, "clicked",
                    G_CALLBACK (on_button_index_update_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_update_index, window_update_index, "window_update_index");
  GLADE_HOOKUP_OBJECT (window_update_index, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (window_update_index, entry8, "entry8");
  GLADE_HOOKUP_OBJECT (window_update_index, label13, "label13");
  GLADE_HOOKUP_OBJECT (window_update_index, button_index_update, "button_index_update");

  return window_update_index;
}

