/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

#include "sys/socket.h"
#include "netinet/in.h"


	int sid,status;
  GtkWidget *window1,*window2,*window_option,*window_delete,*window_update,*window_update_index;

int handle()
{
	int flag=0;
	write(sid,&flag,sizeof(flag));
	kill(getpid(),9);
	
}
int
main (int argc, char *argv[])
{

	
	struct sockaddr_in p;
	int flag;

	signal(2,handle);

	char user[30];
	char pass[30];

	int Len=sizeof(struct sockaddr_in);
	
	sid=socket(PF_INET,SOCK_STREAM,IPPROTO_TCP);
		p.sin_family=PF_INET;
		p.sin_port=3500;
		p.sin_addr.s_addr=inet_addr("192.168.1.30");
	status=connect(sid,&p,Len);
	if(status==-1)
	{
		printf("Connection failed                 [ FAILED ]\n\n");
		exit(0);
	}

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  window1 = create_window1 ();
  gtk_widget_show (window1);
  window2 = create_window2 ();
  gtk_widget_hide (window2);
	window_option=create_window_option();
	gtk_widget_hide(window_option);

	window_delete=create_window_delete();
	gtk_widget_hide(window_delete);

	window_update=create_window_update();
	gtk_widget_hide(window_update);
	

	window_update_index=create_window_update_index();
	gtk_widget_hide(window_update_index);
	
	
  gtk_main ();
  return 0;
}

